name: athos_env
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy=2.2.4
  - pandas=2.2.3
  - scipy=1.15.2
  - scikit-learn=1.7.0
  - matplotlib=3.10.1
  - kiwisolver=1.4.8
  - pymongo=4.13.0
  - sqlalchemy=2.0.40
  - gitpython=3.1.44
  - python-dotenv=0.19.0
  - joblib=1.5.1
  - threadpoolctl=3.6.0
  - packaging=24.2
  - setuptools=78.1.0
  - pip:
    - imbalanced-learn==0.12.2 # Para SMOTE
    - networkx==3.3            # Para Algoritmos Gr√°ficos
    - ipywidgets==8.1.1        # Para la Interfaz Interactiva
    - xgboost==2.0.3           # Modelo ML